/* Database schema to keep the structure of entire database. */

# CREATE TABLE animals(
id integer generated by default as identity
(start with 1 increment by 1),
name char(100),
date_of_birth date,
escape_attemps integer,
neutered boolean,
weight_kg decimal
);