/* Database schema to keep the structure of entire database. */
vet_clinic = CREATE TABLE animals(
    id integer generated by default as identity (start with 1 increment by 1),
    name varchar(100) not null,
    date_of_birth date not null,
    escape_attemps integer not null,
    neutered boolean not null,
    weight_kg decimal not null
);

ALTER TABLE
    animals
ADD
    species varchar(100);

/*New Tables*/
CREATE TABLE owners(
    id INT GENERATED ALWAYS AS IDENTITY,
    full_name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE species(
    id INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

-- Change primary key
ALTER TABLE
    animals
ADD
    PRIMARY KEY(id);

--  Remove species column
ALTER TABLE
    animals DROP COLUMN species;

-- Add species column and set foreign key
ALTER TABLE
    animals
ADD
    COLUMN species_id INT;

ALTER TABLE
    animals
ADD
    FOREIGN KEY (species_id) REFERENCES species (id);

-- Add owners column and set foreign key
ALTER TABLE
    animals
ADD
    COLUMN owner_id INT;

ALTER TABLE
    animals
ADD
    FOREIGN KEY (owner_id) REFERENCES owners (id);

-- New table called vets
CREATE TABLE vets (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    date_of_graduation DATE NOT NULL,
    PRIMARY KEY(id)
);

-- Add join/bridging table
CREATE TABLE specializations (
    species_id INTEGER REFERENCES species(id),
    vet_id INTEGER REFERENCES vets(id),
    PRIMARY KEY (species_id, vet_id)
);

CREATE TABLE visits (
    animal_id INTEGER REFERENCES animals(id),
    vet_id INTEGER REFERENCES vets(id),
    visit_date date,
    PRIMARY KEY (animal_id, vet_id)
);

-- Add an email column to your owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);

--Add indexing for performance
CREATE INDEX index_animal_id ON visits (animal_id);
CREATE INDEX index_id_asc on visits(vet_id ASC);
CREATE INDEX index_email ON owners (email);